[target.x86_64-pc-windows-msvc]
rustflags = [
  "-C",
  "target-feature=+crt-static",
  "-L",
  "native=C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\um\\x64",
  "-L",
  "native=C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\ucrt\\x64",
  "-l",
  "static=psapi",
  "-l",
  "static=shell32",
  "-l",
  "static=advapi32",
]

[target.aarch64-pc-windows-msvc]
rustflags = [
  "-C",
  "target-feature=+crt-static",
  "-L",
  "native=C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\um\\arm64",
  "-L",
  "native=C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\ucrt\\arm64",
  "-l",
  "static=psapi",
  "-l",
  "static=shell32",
  "-l",
  "static=advapi32",
]
