[workspace]
# Official SaVM Build Version
metadata.savm.version = "v0.0.2-buildtest.6"

members = [
  # Sa Runtime Async Helper
  "sart/saffi/libsavmasync",
  "sart/saffi/savmasync",

  # Sa Runtime Allocator
  "sart/saffi/libsalloc",

  # Sa VM (CORE)
  "savm",

  # Sa JIT Library
  "sajit",

  # Sa Runtime
  "sart",

  # Sa Runtime FFI
  "sart/saffi/ffi",

  # Sa Runtime Allocator Interface
  "sart/saffi/salloc",

  # Binaries
  "bin/sapacker",
  "bin/sasm",
  "bin/satest",
  "bin/savmimgrun",
  "bin/savmrt",
  "bin/savmrtcache",
  "bin/savmrun",
  "bin/savmruncore",
  "bin/savmrunshared",
  "bin/savmruntypes",

  # SaVM C Compatible Libraries (Future Experiments currently)
  # Dynamic Linkable AND Static Linkable
  # Depends on the C ABI (musl, glibc, msvc, libSystem)
  "libs/savmc",
  "libs/sasmc",

  # C Prelude Glue (DRY)
  "libs/cprelude",

  # Mixed Radix
  "mixedradix",
  "mixedradix/macros",

  # SaBin Spec
  "libs/sabin_spec",

  # A sane way to compile SaVM Bytecode
  # 
  # This is the SaVM IR Generator
  "libs/sair",

  # Internal Crates - saffine (sa affinity)
  "internal/saffine",

  # SaVM Internal Building Crates
  "savm_build",
  "savm_build_cinder"
]
resolver = "3"

# These are testing and hence should not be directly bundled
exclude = ["sajit/llvmtest", "saw"]

[profile.release]
opt-level = 3
lto = false
codegen-units = 1
panic = "abort"
strip = true
