[workspace]
members = [
  "sart/saffi/libsalloc",
  "sajit",
  "sart",
  "sart/saffi/ffi",
  "sart/saffi/salloc",
  "savm",
  "bin/sapacker",
  "bin/sasm",
  "bin/satest",
  "bin/savmrun",
]
resolver = "3"
exclude = ["jitemission", "sajit/llvmtest"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
