[target.mips64el-unknown-linux-gnuabi64]
build-std = true

[target.loongarch64-unknown-linux-gnu]
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update",
  "apt-get install --assume-yes lld clang",
]

[build.env]
passthrough = ["LIBRARY_PATH", "CFLAGS", "RUSTFLAGS", "LLVM_SYS_221_PREFIX"]
