[build]
build-std = true

[build.env]
passthrough = ["LIBRARY_PATH", "CFLAGS", "RUSTFLAGS", "LLVM_SYS_221_PREFIX"]

[target.arm-unknown-linux-gnueabihf]
rustflags = [
  "-Z",
  "tls-model=global-dynamic",
  "-C",
  "relocation-model=pic",
  "-C",
  "link-arg=-Wl,--allow-shlib-undefined",
  "-L",
  "native=/project/target/arm-unknown-linux-gnueabihf/release",
  "-L",
  "native=/target/arm-unknown-linux-gnueabihf/release",
]
