[target.mips64el-unknown-linux-gnuabi64]
build-std = ["core", "alloc", "proc_macro", "std"]

[target.loongarch64-unknown-linux-gnu]
pre-build = [
  "apt-get update && apt-get install -y wget lsb-release software-properties-common gnupg",
  "wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && ./llvm.sh 22",
  "ln -sf /usr/bin/clang-22 /usr/bin/clang",
  "ln -sf /usr/bin/ld.lld-22 /usr/bin/ld.lld",
]

[target.armv7-unknown-linux-gnueabihf]
dockerfile = "./crossimages/Dockerfile.armv7-unknown-linux-gnueabihf"

[target.powerpc64le-unknown-linux-gnu]
dockerfile = "./crossimages/Dockerfile.powerpc64le-unknown-linux-gnu"

[target.riscv64gc-unknown-linux-gnu]
dockerfile = "./crossimages/Dockerfile.riscv64gc-unknown-linux-gnu"

[build.env]
passthrough = ["LIBRARY_PATH", "CFLAGS", "RUSTFLAGS", "LLVM_SYS_221_PREFIX"]
