#!/bin/sh

if [ ! -d "./llvm" ]; then
  echo "LLVM is not installed - please run './sacli' first to install it" >&2
  exit 1
fi

export LLVM_SYS_221_PREFIX="$(pwd)/llvm/install"

echo "✅ Your session has been loaded with SaVM Required Environment Variables"

if [ -f "$HOME/.bashrc" ]; then . "$HOME/.bashrc"; fi
if [ -f "$HOME/.zshrc" ]; then . "$HOME/.zshrc"; fi