[[IgnoredVulns]]
id = "RUSTSEC-2024-0436"
reason = "The 'paste' crate is unmaintained but necessary for current build; no fix available."

[[IgnoredVulns]]
id = "RUSTSEC-2025-0141"
reason = "The 'bincode' crate is unmaintained but necessary for current build; no fix available."

[[IgnoredVulns]]
id = "RUSTSEC-2026-0194"
reason = "Unupdatable"

[[IgnoredVulns]]
id = "RUSTSEC-2026-0195"
reason = "Unupdatable"

[[IgnoredVulns]]
id = "RUSTSEC-2026-0206"
reason = "No patch available"

[[IgnoredVulns]]
id = "RUSTSEC-2026-0192"
reason = "No patch available"
