[package]
name = "savm"
version = "0.1.0"
edition = "2024"

[dependencies]
# Concurrency Maps
ahash = "^0.8"
evmap = "^11"

# High Speed
rayon = "^1"
moka = { version = "^0.12", features = ["sync"] }

# Macro Helpers
pastey = "^0.2"

# Our concurrency runtime
tokio = { version = "^1", features = ["rt", "rt-multi-thread", "sync", "time"] }

# Sets of compiler
cranelift = { version = "^0.129", features = [
  "module",
  "native",
], optional = true }
llvm-sys = { version = "=221", default-features = false, features = [
  "force-static",
  "disable-alltargets-init",
], optional = true }

# Sa Runtime
sart = { path = "../sart" }

# SaVM Native Linker and CodeAllocator
sajit = { version = "0.0.1", path = "../sajit", optional = true }

[features]
default = ["cranelift"]
llvm = ["dep:llvm-sys", "native"]
cranelift = ["dep:cranelift", "native"]
native = ["dep:sajit"]
