[package]
name = "savm"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"

# license = "AGPL-3.0-only WITH LicenseRef-SaVM-Linking-Exception"
license-file = "../LICENSE"

[dependencies]
# Randomness
rand = { version = "^0.10", default-features = false, features = ["sys_rng"] }

# Concurrency Maps
ahash = "^0.8"
moka = { version = "^0.12", features = ["sync"] }

# Concurrent Units
rayon = "^1"
crossbeam-channel = { version = "^0.5", optional = true }

# Macro Helpers
pastey = "^0.2"

# Our concurrency runtime
tokio = { version = "^1", features = ["rt", "rt-multi-thread", "sync", "time"] }

# Sets of compiler
cranelift = { version = "^0.133", features = [
  "std",
  "native",
  "frontend",
], optional = true }
llvm-sys = { version = "=221.0.1", default-features = false, features = [
  "force-static",
  "disable-alltargets-init",
], optional = true }

# Sa Runtime
sart = { path = "../sart" }

# SaVM Native Linker and CodeAllocator
sajit = { path = "../sajit", optional = true }
serde = { version = "^1", features = ["derive"] }

# Lexical
lexical-core = { version = "^1", default-features = false, features = [
  "write-integers",
] }
mixedradix = { path = "../mixedradix" }

[build-dependencies]
cc = { version = "^1", optional = true }

[features]
default = []

ffi_system = ["sart/ffi_system"]

# Development mode (rust-analyzer)
dev = ["cranelift", "llvm"]

llvm = ["dep:llvm-sys", "dep:cc", "native", "sajit/llvm"]
cranelift = ["dep:cranelift", "native"]
native = ["dep:sajit", "dep:crossbeam-channel", "dag"]

# AcDAG support
dag = []
