name: Build SaVM

description: Builds SaVM

inputs:
  llvmargs:
    description: "SaCLI llvm args"
    required: false
    default: "--llvm-probe"

  feature:
    description: Describe the savmrun feature to build
    required: false
    default: "standard"

  builder:
    description: Name of the builer to use
    required: false
    default: "cargo"

  rusttarget:
    description: Rust Targets to install
    required: false

  argv:
    description: Args to pass to builder
    required: false

  rust:
    description: Should we install rust
    default: "true"
    required: false

  rustflags:
    description: Default rustflags
    required: false

runs:
  using: composite

  steps:
    - name: Setup Rust (Full)
      if: inputs.builder == 'cargo' && inputs.rust == 'true'
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.rusttarget }}
        toolchain: nightly
        components: rustfmt

    - name: Setup Rust (Light)
      if: inputs.builder != 'cargo'
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rust-src,rustfmt
        toolchain: nightly

    - name: Setup NodeJS
      uses: actions/setup-node@v6
      with:
        node-version: ">=24"

    - name: Setup LLVM
      shell: pwsh
      run: |
        ./sacli.ps1 llvm ${{ inputs.llvmargs }}

    - name: Chmod
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: chmod +x ${{ github.workspace }}/llvm/install/bin/*

    - name: Set up GCC (i686)
      if: runner.os == 'Linux' && runner.arch == 'X64'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-multilib g++-multilib

    - name: Set up QEMU
      if: runner.os == 'Linux'
      shell: bash
      run: |
        file /home/runner/work/sa/sa/llvm/install/bin/llvm-config

        sudo apt-get update
        sudo apt-get install -y qemu-user-static binfmt-support

        sudo update-binfmts --enable

    - name: Setup cross
      shell: bash
      if: inputs.builder == 'cross'
      run: |
        cargo install cross --git https://github.com/cross-rs/cross

    - name: Build SaVM
      shell: pwsh
      env:
        DYLD_LIBRARY_PATH: ${{ github.workspace }}/target/${{ inputs.rusttarget }}/release
        LIBRARY_PATH: ${{ github.workspace }}/target/${{ inputs.rusttarget }}/release
        RUST_BACKTRACE: 1
        RUSTC_BOOTSTRAP: 1

        CC_loongarch64_unknown_linux_gnu: clang-22
        AR_loongarch64_unknown_linux_gnu: llvm-ar-22
        CFLAGS_loongarch64_unknown_linux_gnu: >-
          --target=loongarch64-unknown-linux-gnu
          --sysroot=/usr/loongarch64-unknown-linux-gnu -isystem
          /usr/loongarch64-unknown-linux-gnu/include
      run: |
        ./devenv.ps1

        if ("${{ inputs.rusttarget }}" -eq "i686-unknown-linux-gnu") {
          $env:CFLAGS="-fno-stack-protector"
          $env:RUSTFLAGS = "${{ inputs.rustflags }} -C link-arg=-fno-stack-protector"
        }

        ${{ inputs.builder }} build ${{ inputs.argv }} --release -p salloc

        ${{ inputs.builder }} build ${{ inputs.argv }} --release --workspace --no-default-features --features savmrun/${{ inputs.feature }},satest/${{ inputs.feature }}

    - name: Package
      shell: pwsh
      env:
        PACKAGE: savm-${{ inputs.rusttarget }}-${{ inputs.feature }}
        TARGET: ${{ inputs.rusttarget }}
      continue-on-error: true
      run: |
        ./package.ps1

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      continue-on-error: true
      with:
        name: savm-${{ inputs.rusttarget }}-${{ inputs.feature }}
        path: |
          savm-${{ inputs.rusttarget }}-${{ inputs.feature }}.zip
        archive: true
        compression-level: 0
