name: Build SaVM

description: Builds SaVM

inputs:
  llvmargs:
    description: "SaCLI llvm args"
    required: false
    default: "--llvm-probe"

  feature:
    description: Describe the savmrun feature to build
    required: false
    default: "standard"

  builder:
    description: Name of the builer to use
    required: false
    default: "cargo"

  rusttarget:
    description: Rust Targets to install
    required: false

  argv:
    description: Args to pass to builder
    required: false

runs:
  using: composite

  steps:
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.rusttarget }}
        toolchain: nightly

    - name: Setup NodeJS
      uses: actions/setup-node@v6
      with:
        node-version: ">=24"

    - name: Setup LLVM
      shell: pwsh
      run: |
        ./sacli.ps1 llvm ${{ inputs.llvmargs }}

    - name: Build SaVM
      shell: pwsh
      env:
        LIBRARY_PATH: |
          ${{ github.workspace }}/target/release,${{ github.workspace }}/${{ inputs.rusttarget }}/release
      run: |
        ./devenv.ps1

        ${{ inputs.builder }} build --release -p salloc
        ${{ inputs.builder }} build ${{ inputs.argv }} --release --no-default-features --features savmrun/${{ inputs.feature }}
