FROM ubuntu:24.04 AS cross-base
ENV DEBIAN_FRONTEND=noninteractive

COPY crossimages/common.sh crossimages/lib.sh /
RUN sh /common.sh

COPY crossimages/cmake.sh /
RUN sh /cmake.sh

FROM cross-base AS build

RUN apt-get update && apt-get install --assume-yes --no-install-recommends \
    g++-powerpc64le-linux-gnu \
    gfortran-powerpc64le-linux-gnu \
    libc6-dev-ppc64el-cross

COPY crossimages/deny-debian-packages.sh /
RUN TARGET_ARCH=ppc64el /deny-debian-packages.sh \
    binutils \
    binutils-powerpc64le-linux-gnu

COPY crossimages/qemu.sh /
RUN sh /qemu.sh ppc64le softmmu

COPY crossimages/dropbear.sh /
RUN sh /dropbear.sh

COPY crossimages/linux-image.sh /
RUN sh /linux-image.sh powerpc64le

COPY crossimages/linux-runner crossimages/base-runner.sh /
COPY crossimages/toolchain.cmake /opt/toolchain.cmake

ENV CROSS_TOOLCHAIN_PREFIX=powerpc64le-linux-gnu-
ENV CROSS_SYSROOT=/usr/powerpc64le-linux-gnu
ENV CROSS_TARGET_RUNNER="/linux-runner powerpc64le"
ENV CARGO_TARGET_POWERPC64LE_UNKNOWN_LINUX_GNU_LINKER="$CROSS_TOOLCHAIN_PREFIX"gcc \
    CARGO_TARGET_POWERPC64LE_UNKNOWN_LINUX_GNU_RUNNER="$CROSS_TARGET_RUNNER" \
    AR_powerpc64le_unknown_linux_gnu="$CROSS_TOOLCHAIN_PREFIX"ar \
    CC_powerpc64le_unknown_linux_gnu="$CROSS_TOOLCHAIN_PREFIX"gcc \
    CXX_powerpc64le_unknown_linux_gnu="$CROSS_TOOLCHAIN_PREFIX"g++ \
    CMAKE_TOOLCHAIN_FILE_powerpc64le_unknown_linux_gnu=/opt/toolchain.cmake \
    BINDGEN_EXTRA_CLANG_ARGS_powerpc64le_unknown_linux_gnu="--sysroot=$CROSS_SYSROOT -idirafter/usr/include" \
    QEMU_LD_PREFIX="$CROSS_SYSROOT" \
    RUST_TEST_THREADS=1 \
    PKG_CONFIG_PATH="/usr/lib/powerpc64le-linux-gnu/pkgconfig/:${PKG_CONFIG_PATH}" \
    PKG_CONFIG_ALLOW_CROSS=1 \
    CROSS_CMAKE_SYSTEM_NAME=Linux \
    CROSS_CMAKE_SYSTEM_PROCESSOR=ppc64le \
    CROSS_CMAKE_CRT=gnu \
    CROSS_CMAKE_OBJECT_FLAGS="-ffunction-sections -fdata-sections -fPIC -m64"

RUN sed -e "s#@DEFAULT_QEMU_LD_PREFIX@#$QEMU_LD_PREFIX#g" -i /linux-runner
