FROM alpine:edge

# Install all your heavy tools once
RUN apk update && apk add --no-cache \
    llvm22-dev \
    llvm22-static \
    clang22 \
    clang22-libclang \
    lld \
    build-base \
    alpine-sdk \
    libxml2-dev \
    coreutils \
    bash \
    curl \
    nodejs \
    python3 \
    sqlite-dev \
    libffi-dev \
    rustup \
    rust \
    cargo \
    zlib-dev \
    zstd-dev

RUN ln -s /usr/bin/llvm-config-22 /usr/bin/llvm-config