FROM alpine:3.24

# Generate sysroot
RUN apk update && apk add --no-cache \
    llvm-dev \
    llvm-static \
    \
    g++ libstdc++-dev \
    libc++-dev \
    \
    musl-dev \
    libgcc \
    \
    clang22-dev \
    build-base \
    alpine-sdk \
    \
    libxml2-dev \
    libxml2-static \
    \
    sqlite-dev \
    sqlite-static \
    \
    libffi-dev \
    \
    zlib-dev \
    zstd-dev