name: SaVM Build Test

on:
  push:
    branches:
      - main
    paths:
      - ./bin/**/*
      - ./savm/**/*

  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      artifact:
        description: "Force giving artifacts"
        required: true
        type: string
        default: "true"

permissions:
  contents: read
  attestations: write

jobs:
  win32:
    name: Build SaVM ${{ matrix.feature }} (${{ matrix.target }})

    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        target:
          [
            x86_64-pc-windows-msvc,
            aarch64-pc-windows-msvc,
            i686-pc-windows-msvc,
          ]
        feature: [nano, standard, pro, pro_standard]

        exclude:
          - target: i686-pc-windows-msvc
            feature: standard

          - target: i686-pc-windows-msvc
            feature: pro_standard

    runs-on: windows-11-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build SaVM
        uses: ./.github/actions/build-savm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          llvmargs: --llvm-build=llvm-static-${{ matrix.target }}.tar.gz
          llvmver: llvm-static-${{ matrix.target }}.tar.gz
          feature: ${{ matrix.feature }}
          rusttarget: ${{ matrix.target }}
          argv: --target ${{ matrix.target }}

      - name: Dryrun satest
        shell: pwsh
        continue-on-error: true
        working-directory: bin/satest
        run: |
          ${{ github.workspace }}/target/${{ matrix.target }}/release/satest

  darwin:
    name: Build SaVM ${{ matrix.feature }} (${{ matrix.target[0] }})

    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        target:
          [
            [x86_64-apple-darwin, x86_64-apple-darwin],
            [aarch64-apple-darwin, arm64-apple-darwin],
          ]
        feature: [nano, standard, pro, pro_standard]

    runs-on: ${{ matrix.target[0] == 'aarch64-apple-darwin' && 'macos-15' ||
      'macos-15-intel' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build SaVM
        uses: ./.github/actions/build-savm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          llvmargs: --llvm-build=llvm-static-${{ matrix.target[1] }}.tar.gz
          llvmver: llvm-static-${{ matrix.target }}.tar.gz
          feature: ${{ matrix.feature }}
          rusttarget: ${{ matrix.target[0] }}
          argv: --target ${{ matrix.target[0] }}

      - name: Dryrun satest
        shell: pwsh
        continue-on-error: true
        working-directory: bin/satest
        run: |
          ${{ github.workspace }}/target/${{ matrix.target[0] }}/release/satest

  linux:
    name: Build SaVM ${{ matrix.feature }} (${{ matrix.target[0] }})

    strategy:
      fail-fast: true
      max-parallel: 5
      matrix:
        feature: [nano, standard, pro, pro_standard]
        target:
          [
            [aarch64-unknown-linux-gnu, aarch64-linux-gnu],
            [x86_64-unknown-linux-gnu, x86_64-linux-gnu],
            [i686-unknown-linux-gnu, i686-linux-gnu],
          ]

        include:
          - os: ubuntu-24.04-arm
            target: [aarch64-unknown-linux-gnu, aarch64-linux-gnu]

        exclude:
          - target: [i686-unknown-linux-gnu, i686-linux-gnu]
            feature: standard

          - target: [i686-unknown-linux-gnu, i686-linux-gnu]
            feature: pro_standard

    runs-on: ${{ matrix.os || 'ubuntu-latest' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build SaVM
        uses: ./.github/actions/build-savm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          llvmargs: --llvm-build=llvm-static-${{ matrix.target[1] }}.tar.gz
          llvmver: llvm-static-${{ matrix.target }}.tar.gz
          feature: ${{ matrix.feature }}
          rusttarget: ${{ matrix.target[0] }}
          argv: --target ${{ matrix.target[0] }}

      - name: Dryrun satest
        shell: pwsh
        continue-on-error: true
        working-directory: bin/satest
        run: |
          sudo cp ${{ github.workspace }}/target/${{ matrix.target[0] }}/release/libsalloc.so /usr/lib/libsalloc.so
          sudo cp ${{ github.workspace }}/target/${{ matrix.target[0] }}/release/libsavmasync.so /usr/lib/libsavmasync.so
          sudo ldconfig

          ${{ github.workspace }}/target/${{ matrix.target[0] }}/release/satest

  linux_crosscompile:
    name: Build SaVM ${{ matrix.target.feature }} (${{ matrix.target.rust }})

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        target:
          # Armv7 (HF)
          - rust: armv7-unknown-linux-gnueabihf
            clang: armv7-linux-gnueabihf
            llvm: arm-linux-gnueabihf
            feature: nano
            arch: armhf

          - rust: armv7-unknown-linux-gnueabihf
            clang: armv7-linux-gnueabihf
            llvm: arm-linux-gnueabihf
            feature: pro
            arch: armhf

          # PowerPC 64-bit
          - rust: powerpc64le-unknown-linux-gnu
            clang: powerpc64le-linux-gnu
            feature: nano
            arch: ppc64el

          - rust: powerpc64le-unknown-linux-gnu
            clang: powerpc64le-linux-gnu
            feature: pro

            arch: ppc64el

          # RISC-V 64-bit (gc)
          - rust: riscv64gc-unknown-linux-gnu
            clang: riscv64-linux-gnu
            feature: nano
            arch: riscv64
            cpu: rv64

          - rust: riscv64gc-unknown-linux-gnu
            clang: riscv64-linux-gnu
            feature: standard

            arch: riscv64
            cpu: rv64

          - rust: riscv64gc-unknown-linux-gnu
            clang: riscv64-linux-gnu
            feature: pro

            arch: riscv64
            cpu: rv64

          - rust: riscv64gc-unknown-linux-gnu
            clang: riscv64-linux-gnu
            feature: pro_standard

            arch: riscv64
            cpu: rv64

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: ">=24"

      - name: Setup Rustup
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src,rustfmt
          toolchain: nightly

      - name: Setup LLVM
        shell: pwsh
        run: |
          ./sacli.ps1 llvm --llvm-build=llvm-static-${{ matrix.target.llvm || matrix.target.clang }}.tar.gz
        env:
          LLVMENV_VERSION: llvm-static-${{ matrix.target.llvm || matrix.target.clang }}.tar.gz

      - name: Build SaVM
        run: |
          # Retry loop for the main build script
          success=false
          for i in {1..5}; do
            echo "Attempt $i of 5: Running build.sh..."
            if bash ./scripts/savm/sysroot.sh; then
              if bash ./scripts/savm/build.sh; then
                success=true
                break
              fi
            fi
            echo "Attempt $i failed. Waiting 5 seconds before retrying..."
            sleep 5
          done

          if [ "$success" = false ]; then
            echo "Build failed completely after 5 attempts."
            exit 1
          fi
        env:
          LLVM_SYS_221_PREFIX: ${{ github.workspace }}/llvm/install
          ARCH: ${{ matrix.target.arch }}
          TARGET: ${{ matrix.target.rust }}
          CTARGET: ${{ matrix.target.clang }}
          EXTRA: --features savmrunshared/${{ matrix.target.feature }},satest/${{ matrix.target.feature }}${{ matrix.target.c }}

          # Linker
          DYLD_LIBRARY_PATH: ${{ github.workspace }}/target/${{ matrix.target.rust }}/release
          LIBRARY_PATH: ${{ github.workspace }}/target/${{ matrix.target.rust }}/release

      - name: Dryrun satest
        continue-on-error: true
        run: |
          bash ./scripts/savm/testing.sh
        env:
          TARGET: ${{ matrix.target.rust }}
          QEMU_CPU: ${{ matrix.target.cpu }}

      - name: Package
        shell: pwsh
        env:
          PACKAGE: savm-${{ matrix.target.rust }}-${{ matrix.target.feature }}
          TARGET: ${{ matrix.target.rust }}
        continue-on-error: true
        run: |
          cargo install --force cargo-expand
          cargo install --force cbindgen

          ./package.ps1

      - name: Upload Artifact
        uses: Wandalen/wretry.action@e94c43bf2e865e7dbbd90b0c1061053f5888932a
        with:
          action: actions/upload-artifact@v7
          with: |
            name: savm-${{ matrix.target.rust }}-${{ matrix.target.feature }}
            path: |
              savm-${{ matrix.target.rust }}-${{ matrix.target.feature }}.zip
            archive: true
            compression-level: 7

  linux_musl:
    name: Build SaVM ${{ matrix.feature.build }} (${{ matrix.config.target }})

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        feature:
          - build: nano

          - build: pro

        config:
          - target: x86_64-unknown-linux-musl
            platform: linux/amd64
            os: ubuntu-latest

          - target: i686-unknown-linux-musl
            platform: linux/386
            os: ubuntu-latest

          - target: aarch64-unknown-linux-musl
            platform: linux/arm64/v8
            os: ubuntu-24.04-arm

          - target: armv7-unknown-linux-musleabihf
            platform: linux/arm/v7
            os: ubuntu-24.04-arm

          - target: riscv64gc-unknown-linux-musl
            platform: linux/riscv64
            os: ubuntu-24.04-arm

          - target: powerpc64le-unknown-linux-musl
            platform: linux/ppc64le
            os: ubuntu-24.04-arm

        include:
          # X64
          - feature:
              build: standard

            config:
              target: x86_64-unknown-linux-musl
              platform: linux/amd64
              os: ubuntu-latest

          - feature:
              build: pro_standard

            config:
              target: x86_64-unknown-linux-musl
              platform: linux/amd64
              os: ubuntu-latest

          # ARM64
          - feature:
              build: standard

            config:
              target: aarch64-unknown-linux-musl
              platform: linux/arm64/v8
              os: ubuntu-24.04-arm

          - feature:
              build: pro_standard

            config:
              target: aarch64-unknown-linux-musl
              platform: linux/arm64/v8
              os: ubuntu-24.04-arm

          # RISCV64
          - feature:
              build: standard

            config:
              target: riscv64gc-unknown-linux-musl
              platform: linux/riscv64
              os: ubuntu-24.04-arm

          - feature:
              build: pro_standard

            config:
              target: riscv64gc-unknown-linux-musl
              platform: linux/riscv64
              os: ubuntu-24.04-arm

    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup Rustup
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src,rustfmt
          toolchain: nightly

      - name: Install Podman + QEMU
        run: |
          sudo apt update
          sudo apt install podman qemu-user-static binfmt-support

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          key: savm_${{ matrix.config.target }}_${{ matrix.feature.build }}

      - name: Build
        working-directory: muslbuilds
        run: |
          sudo podman build --platform "${{ matrix.config.platform }}" -t ahqrt-build-base:latest .

          export TARGET_PLATFORM="${{ matrix.config.platform }}"
          export FEATURES=',savmrunshared/${{ matrix.feature.build }},satest/${{ matrix.feature.build }}${{ matrix.feature.c }}'

          bash ./build.sh

      - name: Package
        shell: pwsh
        env:
          PACKAGE: savm-${{ matrix.config.target }}-${{ matrix.feature.build }}
          TARGET: ""
        continue-on-error: true
        run: |
          cargo install --force cargo-expand
          cargo install --force cbindgen

          ./package.ps1

      - name: Upload Artifact
        uses: Wandalen/wretry.action@e94c43bf2e865e7dbbd90b0c1061053f5888932a
        with:
          action: actions/upload-artifact@v7
          with: |
            name: savm-${{ matrix.config.target }}-${{ matrix.feature.build }}
            path: |
              savm-${{ matrix.config.target }}-${{ matrix.feature.build }}.zip
            archive: true
            compression-level: 7

  package_m:
    name: Package Installers (macOS)

    runs-on: macos-latest

    needs: [darwin]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Rustup
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src,rustfmt
          toolchain: nightly

      - name: Download & Build Installers
        shell: pwsh
        run: |
          gh run download ${{ github.run_id }} --dir release

          ./extract.ps1
          ./build.ps1
        env:
          GH_TOKEN: ${{ github.token }}
          LINBUILD: false
        working-directory: scripts/build

      - name: Upload Artifact
        uses: Wandalen/wretry.action@e94c43bf2e865e7dbbd90b0c1061053f5888932a
        with:
          action: actions/upload-artifact@v7
          with: |
            name: macos-images
            path: |
              ./scripts/build/outputs/**/*
            archive: true
            compression-level: 9

  package_w:
    name: Package Installers (Windows)

    runs-on: windows-latest

    needs: [win32]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Rustup
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src,rustfmt
          toolchain: nightly

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          key: savm_windows_builder
          workspaces: |
            ./scripts/build -> target

      - name: Download & Build Installers
        shell: pwsh
        run: |
          gh run download ${{ github.run_id }} --dir release

          ./extract.ps1
          ./build.ps1
        env:
          GH_TOKEN: ${{ github.token }}
          LINBUILD: false
        working-directory: scripts/build

      - name: Upload Artifact
        uses: Wandalen/wretry.action@e94c43bf2e865e7dbbd90b0c1061053f5888932a
        with:
          action: actions/upload-artifact@v7
          with: |
            name: windows-images
            path: |
              ./scripts/build/outputs/**/*
            archive: true
            compression-level: 9

  package_wlm:
    name: Package Installers

    runs-on: ubuntu-latest

    needs: [win32, linux_crosscompile, linux, linux_musl, package_m, package_w]

    permissions:
      contents: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Rustup
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src,rustfmt
          toolchain: nightly

      - name: Setup GoLang
        uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: false

      - name: Install nFPM
        run: go install github.com/savmlang/nfpm/v2/cmd/nfpm@main

      - name: Download & Build Installers
        shell: pwsh
        run: |
          gh run download ${{ github.run_id }} --dir release

          ./extract.ps1
          ./build.ps1
        env:
          GH_TOKEN: ${{ github.token }}
          LINBUILD: true
        working-directory: scripts/build

      - name: Generate timestamp
        id: time
        shell: pwsh
        run: |
          # Native PowerShell method to format date cleanly on Windows
          $timestamp = Get-Date -Format "yyyy-MM-dd-HH-mm"
          echo "time=$timestamp" >> $env:GITHUB_OUTPUT

      - name: Upload Artifact
        uses: Wandalen/wretry.action@e94c43bf2e865e7dbbd90b0c1061053f5888932a
        if: inputs.artifact == 'true'
        with:
          action: actions/upload-artifact@v7
          with: |
            name: final-release-assets
            path: |
              ./scripts/build/outputs/**/*
              ./scripts/build/release/**/*.zip
            archive: true
            compression-level: 9

      - name: Release Artifacts
        uses: softprops/action-gh-release@v3
        id: release
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        with:
          tag_name: savmdryrun-${{ steps.time.outputs.time }}
          prerelease: true
          draft: true
          body: |
            Uploaded at : ${{ steps.time.outputs.time }}

            This is an autogenerated build of the whole of SaVM.
          files: |
            ./scripts/build/outputs/**/*
            ./scripts/build/release/**/*.zip

      - name: Undraft
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: gh release edit savmdryrun-${{ steps.time.outputs.time }} --draft=false
        env:
          GH_TOKEN: ${{ github.token }}
          LINBUILD: true
