name: Build

on:
  push:
    tags:
      - v*

permissions:
  contents: write
  attestations: write

jobs:
  build:
    name: Build SaVM
    uses: ./.github/workflows/buildtest.yml

    with:
      artifact: "true"

  publish:
    name: Publish Official SaVM
    needs: [build]

    runs-on: ubuntu-latest

    environment:
      name: Publishing

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Rustup
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src,rustfmt
          toolchain: nightly

      - name: Restore GPG key
        working-directory: scripts/build/nfpm
        run: |
          cat << 'EOF' > key.gpg
          ${{ secrets.GPG_KEY }}
          EOF

      - name: Generate timestamp
        id: version
        shell: pwsh
        run: |
          $version = $(./scripts/build/getVersion.ps1)
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Download & Build Installers
        shell: pwsh
        run: |
          gh run download ${{ github.run_id }} --dir release

          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update
          sudo apt install nfpm

          ./extract.ps1
        env:
          GH_TOKEN: ${{ github.token }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          NFPM_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        working-directory: scripts/build

      - name: Release Artifacts
        uses: softprops/action-gh-release@v3
        id: release
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        with:
          tag_name: v${{ steps.version.outputs.version }}
          draft: true
          body: |
            This is an autogenerated build of the whole of SaVM.
          files: |
            ./scripts/build/outputs/**/*
            ./scripts/build/release/**/*.zip

      - name: Undraft
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: gh release edit v${{ steps.version.outputs.version }} --draft=false
        env:
          GH_TOKEN: ${{ github.token }}
          LINBUILD: true
