name: Test SaVM

on:
  push:

jobs:
  init:
    name: Run test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - uses: actions/setup-node@v6
        with:
          node-version: ">=24"

      - uses: actions/setup-python@v6
        with:
          python-version: "3.9"

      - name: Install salloc
        working-directory: sart/saffi/libsalloc/allocator
        run: |
          cargo build --release

          sudo cp ./target/release/libsalloc.so /usr/lib/libsalloc.so
          sudo ldconfig

      - name: Run
        working-directory: bin/satest
        run: |
          cargo run --release

          echo "Python (Test #1)"
          python bench/1.py

          echo "Python (Test #2)"
          python bench/2.py

          echo "NodeJS (Test #1)"
          node bench/1.js

          echo "NodeJS (Test #1 - No JIT)"
          node --jitless bench/1_nopt.js

          echo "NodeJS (Test #2)"
          node bench/2.js

          echo "NodeJS (Test #2 - No JIT)"
          node --jitless bench/2_nopt.js
