name: Test SaVM

on:
  push:

jobs:
  jitemitvm:
    name: Run jitemission

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: Run
        env:
          LIBRARY_PATH: ${{ github.workspace }}/target/release
        run: |
          chomod +x ./sacli
          ./sacli llvm --llvm-probe
          . ./devenv

          cargo build --release

          cd jitemission
          cargo run --release --package jitemission

  init:
    name: Run test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - uses: actions/setup-node@v6
        with:
          node-version: ">=24"

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Run
        env:
          LIBRARY_PATH: ${{ github.workspace }}/target/release
        run: |
          chomod +x ./sacli
          ./sacli llvm --llvm-probe
          . ./devenv

          cargo build --release

          cd bin/satest
          cargo run --release --package satest

          echo "Python (Test #1)"
          python bench/1.py

          echo "Python (Test #2)"
          python bench/2.py

          echo "NodeJS (Test #1)"
          node bench/1.js

          echo "NodeJS (Test #1 - No JIT)"
          node --jitless bench/1_nopt.js

          echo "NodeJS (Test #2)"
          node bench/2.js

          echo "NodeJS (Test #2 - No JIT)"
          node --jitless bench/2_nopt.js
